### ISSUE TITLE
Rebasing on master

### ISSUE THREAD

**Issue by plwalters** [ultragtx/lcoin#1]
Currently the repo is 60ish commits behind bcoin-org/bcoin master, is it worth the time for me to PR rebasing on top of master?

I don't think the PR would be very compatible but at least you could promote that branch to master if it looks good to you.

**Comment by ultragtx** [comment]
The purpose of this fork was to help litecore catch up with bitcore v5.0, I
still hope bcoin.org can update their lcoin rapidly, so I'm not sure yet if
I will maintain this poject in the future.
Maybe it's easier to have your own fork for now.

Patrick Walters <notifications@github.com>于2017年11月19日 周日下午1:08写道：

**Comment by plwalters** [comment]
Ah I see.  They have deprecated their lcoin fork for now until bcoin is updated.

Thanks for the info, I'll plan accordingly and stop bugging you about this fork then ;)
