### ISSUE TITLE
Fixing broken tests

### ISSUE THREAD

**Issue by plwalters** [ultragtx/lcoin#2]
Currently the bcoin-org fork of lcoin has all tests passing including the ones broken in this repo.  I don't think I understand why the tests are broken yet but I can try to run a diff against the bcoin-org port and see what differences exist.

Does this sound like a good approach or do you have any tips on what might need work to get them working?

**Comment by ultragtx** [comment]
Fixing block-test and tx test is not very easy, you need to generate the litecoin version of thoses files under test/data

**Comment by ultragtx** [comment]
bcoin.org/lcoin didn't do that either.
